GET http://localhost:4000/login/

###
GET http://localhost:3000/protected/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjYwMDk3NTEsImV4cCI6MTY2NjAxMDM1MX0.I0tZDTX9_fwibw6xYuNs1iWL9uYzRSCX_78nbboezA4A0hsYp09VkS3lnekMMPnFmQ_XCVK0hyRNd16weXuvdu-TwCqWw9wuMLmJNYHgDHaoEEPscmlvpbmikIXaIVaMJG8h3cKPZVQo8lR-aRJ5w-X-gy1UguSotFoDpcGBz09cO9P9SKtrvWFj-pmkhnWjteGjvqXrObSuGdY0yuDziv85mfsYmWNkyHD2lkDzUxZgBefDG8MMZW1q9Ded23PyCZijheptoHQu0dJzmTKHfx6wC2oWgkh9-XOSKi-cXwWXKvhPPCfplESeZFgV0OvHcuOUbl52dRWWcQ225-05lvdNXtP8OKahUjRCeVTwRNjcrZbw6Y3b-8nxtHV2e5TcWr06Xkpbng-hcTBzKKSYYXAhb0SHkyVBEbD9gpxhGdfmOXcdY4Ei6_68WL5QW8YZHyw3Xu9J7qoTig2xTxztIGKq3Uv3BaWXshH7ImGhWYXWM3A4CcDb8M_PxfhYIWFE

